apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: team-ai-main-ingress
  namespace: distributed-team-ai-ns
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: "nginx"
  rules:
  # 1. Main Website Route (The Frontend!)
  - host: "team-ai.live"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: team-ai-frontend
            port:
              number: 80
              
  - host: "www.team-ai.live"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: team-ai-frontend
            port:
              number: 80

  # 2. Previews Route
  - host: "*.previews.team-ai.live"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: distributed-team-ai-proxy
            port:
              number: 80
  
  # 3. API Gateway Route
  - host: "api.team-ai.live"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port:
              number: 80